# Generated by Django 5.2.11 on 2026-03-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='test_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='test_questions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='test_result',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='test_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('interview', 'Test en attente'), ('reviewed', 'Examinée'), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], default='pending', max_length=20),
        ),
    ]
