# Generated by Django 5.2.11 on 2026-04-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_test_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
