# Generated by Django 5.2.11 on 2026-04-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_status',
            field=models.CharField(choices=[('not_scheduled', 'Non programmé'), ('scheduled', 'Programmé'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='not_scheduled', max_length=20),
        ),
    ]
