# Generated by Django 5.2.11 on 2026-04-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_interview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('interview', 'Test en attente'), ('reviewed', 'Examinée'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('interview_scheduled', 'Entretien programmé')], default='pending', max_length=20),
        ),
    ]
