# Generated by Django 5.2.10 on 2026-05-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('interview', 'Test en attente'), ('reviewed', 'Examinée'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('programme_entretien', 'Entretien programmé')], default='pending', max_length=20),
        ),
    ]
