# Generated by Django 5.2.11 on 2026-04-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='auth_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
