# Generated by Django 5.2.11 on 2026-02-27 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Interim', 'Intérim'), ('Stage', 'Stage'), ('Alternance', 'Alternance'), ('Freelance', 'Freelance')], max_length=20)),
                ('experience_level', models.CharField(choices=[('0-1', "Moins d'un an"), ('1-3', '1 à 3 ans'), ('3-5', '3 à 5 ans'), ('5-10', '5 à 10 ans'), ('10+', 'Plus de 10 ans')], max_length=10)),
                ('education_level', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('remote_possible', models.BooleanField(default=False)),
                ('skills_required', models.JSONField(default=list)),
                ('skills_preferred', models.JSONField(blank=True, default=list)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_visible', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Fermée'), ('draft', 'Brouillon')], default='draft', max_length=20)),
                ('views_count', models.IntegerField(default=0)),
                ('applications_count', models.IntegerField(default=0)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='companies.recruiterprofile')),
            ],
            options={
                'db_table': 'job_offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
