# Generated by Django 5.2.11 on 2026-02-24 13:58

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_user_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=profiles.models.user_photo_path)),
                ('cv', models.FileField(blank=True, null=True, upload_to=profiles.models.user_cv_path)),
                ('cv_file_name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('experience', models.CharField(blank=True, choices=[('0-1', "Moins d'un an"), ('1-3', '1 à 3 ans'), ('3-5', '3 à 5 ans'), ('5-10', '5 à 10 ans'), ('10+', 'Plus de 10 ans')], max_length=10)),
                ('education', models.CharField(blank=True, choices=[('bac', 'Baccalauréat'), ('bac+2', 'Bac+2 (BTS, DUT)'), ('bac+3', 'Bac+3 (Licence)'), ('bac+5', 'Bac+5 (Master, Ingénieur)'), ('bac+8', 'Bac+8 (Doctorat)')], max_length=10)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil candidat',
                'verbose_name_plural': 'Profils candidats',
            },
        ),
    ]
