# Generated by Django 5.2.10 on 2026-03-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='cv_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
