# Generated by Django 5.2.10 on 2026-03-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_candidateprofile_cv_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='cv_parsed',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='cv_parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
