# Generated by Django 5.2.11 on 2026-04-10 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('profiles', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='is_starred',
            field=models.BooleanField(default=False, help_text='Candidat marqué comme talent exceptionnel'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='star_category',
            field=models.CharField(blank=True, choices=[('exceptional', '💎 Exceptionnel (90-100)'), ('excellent', '⭐ Excellent (75-89)'), ('good', '👍 Bon potentiel (60-74)'), ('manual', '👤 Ajout manuel')], help_text='Catégorie du talent', max_length=50),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='star_reason',
            field=models.CharField(blank=True, help_text='Raison pour laquelle ce candidat est étoilé', max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='star_score',
            field=models.IntegerField(default=0, help_text='Score objectif (0-100) basé sur expérience, diplômes, etc.'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='starred_at',
            field=models.DateTimeField(blank=True, help_text="Date d'ajout à la talent pool", null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='starred_by',
            field=models.ForeignKey(blank=True, help_text='Recruteur qui a étoilé ce candidat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starred_candidates', to='companies.recruiterprofile'),
        ),
    ]
