# Generated by Django 5.2.11 on 2026-04-13 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('profiles', '0005_candidateprofile_is_starred_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='is_starred',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='star_category',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='star_reason',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='star_score',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='starred_at',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='starred_by',
        ),
        migrations.CreateModel(
            name='TalentPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Pourquoi ce candidat a été ajouté au vivier ?', null=True)),
                ('score', models.IntegerField(default=0, help_text='Score de qualité du CV (0-100)')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_pool_entries', to='profiles.candidateprofile')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_pool', to='companies.recruiterprofile')),
            ],
            options={
                'verbose_name': 'Talent (vivier)',
                'verbose_name_plural': 'Talents (vivier)',
                'db_table': 'talent_pool',
                'ordering': ['-score', '-added_at'],
                'unique_together': {('recruiter', 'candidate')},
            },
        ),
    ]
