# Generated by Django 5.2.11 on 2026-04-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_candidateprofile_is_starred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentpool',
            name='domain',
            field=models.CharField(blank=True, help_text='Domaine principal du candidat (ex: Développeur Full Stack, Data Scientist)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='talentpool',
            name='years_experience',
            field=models.IntegerField(default=0, help_text="Années d'expérience extraites du CV"),
        ),
    ]
