# Generated by Django 5.2.11 on 2026-04-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_talentpool_domain_talentpool_years_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
